diseases_en = [
    'human immunodeficiency virus',
    '2019 novel coronavirus',
    'takotsubo cardiomyopathy',
    'tuberculoses',
    'endocarditis',
    'syphilis',
    'hypertension',
    'sarcoid',
    'hepatitis b',
    'ulcerative colitis',
    'crohn disease',
    'chagas disease',
    'diastolic dysfunction',
    'goiter',
    'arthritis',
    'repetitive stress syndrome',
    'flu',
    'suicide',
    'visual anomalies',
    'loss of sex drive',
    'spotting problems',
    'perforated ulcer',
    'ibs',
    'acne',
    'achilles tendinitis',
    'bipolar disorder',
    'hyperthyroid',
    'hypothyroid',
    'acute kidney failure',
    'deafness',
    'hypochondria',
    'gingival disease',
    'disability',
    'osteoarthritis',
    'mi',
    'lyme disease',
    'labyrinthitis',
    'fibromyalgia',
    'multiple sclerosis',
    'acute gastritis',
    'muscle inflammation',
    "alzheimer's",
    'gastric problems',
    'oesophageal ulcer',
    'polymyositis',
    'bronchitis',
    "parkinson's disease",
    'restless legs syndrome',
    'inflammatory disorder of tendon',
    'mood disorder of depressed type',
    'sinus infection',
    'mnd',
    'permanent nerve damage',
    'gall bladder disease',
    'infection',
    'sepsis',
    'menopause',
    'eczema',
    'type two diabetic',
    'type one diabetic',
    'parkinson',
    'cardiovascular disease',
    'learning problems',
    'dementia',
    'chronic fatigue syndrome',
    'coronary artery disease',
    'upper respiratory infection',
    'alopecia',
    'sexual dysfunction',
    'nerve damage',
    'carpal tunnel syndrome',
    'liver failure',
    'tinnitus',
    'malaria',
    'phlebitis',
    'diarrhoea',
    'vision problems',
    'aortic aneurysem',
    'urinary tract infection',
    'psychosis',
    'rheumatoid arthritis',
    'diabetes',
    'stevens johnson syndrome',
    'mental illness',
    'pancreatitis',
    'adenomyosis',
    'als',
    'chronic kidney disease',
    'endometriosis',
    'asthma',
    'lupus',
    'pneumonia',
    'arrhythmia'
]

diseases_zh = [
    "人类免疫缺陷病毒",
    "2019新型冠状病毒",
    "章鱼罐心肌病",
    "结核",
    "心内膜炎",
    "梅毒",
    "高血压",
    "结节病",
    "乙型肝炎",
    "溃疡性结肠炎",
    "克罗恩病",
    "查加斯病",
    "舒张功能障碍",
    "甲状腺肿",
    "关节炎",
    "重复劳损综合征",
    "流感",
    "自杀",
    "视觉异常",
    "性欲丧失",
    "发现问题",
    "穿孔性溃疡",
    "肠易激综合症",
    "痤疮",
    "跟腱炎",
    "躁郁症",
    "甲状腺功能亢进",
    "甲状腺功能减退",
    "急性肾衰竭",
    "耳聋",
    "疑病症",
    "牙龈疾病",
    "残疾",
    "骨关节炎",
    "心肌梗塞",
    "莱姆病",
    "迷路炎",
    "纤维肌痛",
    "多发性硬化",
    "急性胃炎",
    "肌肉炎",
    "阿尔茨海默病",
    "胃部问题",
    "食管溃疡",
    "多发性肌炎",
    "支气管炎",
    "帕金森病",
    "不宁腿综合症",
    "肌腱炎症性疾病",
    "抑郁症",
    "鼻窦感染",
    "运动神经元疾病",
    "永久性神经损伤",
    "胆囊疾病",
    "感染",
    "败血症",
    "更年期",
    "湿疹",
    "2型糖尿病",
    "1型糖尿病",
    "帕金森氏症",
    "心血管疾病",
    "学习障碍",
    "痴呆",
    "慢性疲劳综合症",
    "冠状动脉疾病",
    "上呼吸道感染",
    "脱发",
    "性功能障碍",
    "神经损伤",
    "腕管综合征",
    "肝衰竭",
    "耳鸣",
    "疟疾",
    "静脉炎",
    "腹泻",
    "视力问题",
    "主动脉瘤",
    "尿路感染",
    "精神病",
    "风湿性关节炎",
    "糖尿病",
    "史蒂文斯-约翰逊综合症",
    "精神疾病",
    "胰腺炎",
    "腺肌症",
    "肌萎缩侧索硬化症",
    "慢性肾脏病",
    "子宫内膜异位症",
    "哮喘",
    "红斑狼疮",
    "肺炎",
    "心律失常"
]

diseases_fr = [
    "virus de l'immunodéficience humaine",
    "coronavirus novel 2019",
    "cardiomyopathie de Takotsubo",
    "tuberculose",
    "endocardite",
    "syphilis",
    "hypertension",
    "sarcoïdose",
    "hépatite B",
    "colite ulcéreuse",
    "maladie de Crohn",
    "maladie de Chagas",
    "dysfonction diastolique",
    "goitre",
    "arthrite",
    "syndrome de stress répétitif",
    "grippe",
    "suicide",
    "anomalies visuelles",
    "perte de libido",
    "problèmes de spotting",
    "ulcère perforé",
    "syndrome du côlon irritable",
    "acné",
    "tendinite d'Achille",
    "trouble bipolaire",
    "hyperthyroïdie",
    "hypothyroïdie",
    "insuffisance rénale aiguë",
    "surdité",
    "hypochondrie",
    "maladie gingivale",
    "handicap",
    "ostéoarthrite",
    "infarctus du myocarde",
    "maladie de Lyme",
    "labyrinthite",
    "fibromyalgie",
    "sclérose en plaques",
    "gastrite aiguë",
    "inflammation musculaire",
    "maladie d'Alzheimer",
    "problèmes gastriques",
    "ulcère oesophagien",
    "polymyosite",
    "bronchite",
    "maladie de Parkinson",
    "syndrome des jambes sans repos",
    "trouble inflammatoire des tendons",
    "trouble de l'humeur de type dépressif",
    "infection des sinus",
    "maladie du motoneurone",
    "dommages nerveux permanents",
    "maladie de la vésicule biliaire",
    "infection",
    "sepsis",
    "ménopause",
    "eczéma",
    "diabète de type deux",
    "diabète de type un",
    "Parkinson",
    "maladie cardiovasculaire",
    "problèmes d'apprentissage",
    "démence",
    "syndrome de fatigue chronique",
    "maladie coronarienne",
    "infection des voies respiratoires supérieures",
    "alopécie",
    "dysfonction sexuelle",
    "dommages aux nerfs",
    "syndrome du canal carpien",
    "insuffisance hépatique",
    "acouphènes",
    "paludisme",
    "phlébite",
    "diarrhée",
    "problèmes de vision",
    "anévrisme aortique",
    "infection urinaire",
    "psychose",
    "arthrite rhumatoïde",
    "diabète",
    "syndrome de Stevens-Johnson",
    "maladie mentale",
    "pancréatite",
    "adénomyose",
    "SLA",
    "maladie rénale chronique",
    "endométriose",
    "asthme",
    "lupus",
    "pneumonie",
    "arythmie"
]

diseases_es = [
    "virus de inmunodeficiencia humana",
    "coronavirus novel de 2019",
    "cardiomiopatía de Takotsubo",
    "tuberculosis",
    "endocarditis",
    "sífilis",
    "hipertensión",
    "sarcoidosis",
    "hepatitis B",
    "colitis ulcerosa",
    "enfermedad de Crohn",
    "enfermedad de Chagas",
    "disfunción diastólica",
    "bocio",
    "artritis",
    "síndrome de estrés repetitivo",
    "gripe",
    "suicidio",
    "anomalías visuales",
    "pérdida del deseo sexual",
    "problemas de detección",
    "úlcera perforada",
    "síndrome del intestino irritable",
    "acné",
    "tendinitis del Aquiles",
    "trastorno bipolar",
    "hipertiroidismo",
    "hipotiroidismo",
    "insuficiencia renal aguda",
    "sordera",
    "hipocondría",
    "enfermedad gingival",
    "discapacidad",
    "osteoartritis",
    "infarto de miocardio",
    "enfermedad de Lyme",
    "laberintitis",
    "fibromialgia",
    "esclerosis múltiple",
    "gastritis aguda",
    "inflamación muscular",
    "enfermedad de Alzheimer",
    "problemas gástricos",
    "úlcera esofágica",
    "polimiositis",
    "bronquitis",
    "enfermedad de Parkinson",
    "síndrome de piernas inquietas",
    "trastorno inflamatorio del tendón",
    "trastorno del ánimo de tipo depresivo",
    "infección sinusal",
    "enfermedad de la neurona motora",
    "daño nervioso permanente",
    "enfermedad de la vesícula biliar",
    "infección",
    "sepsis",
    "menopausia",
    "eczema",
    "diabético tipo dos",
    "diabético tipo uno",
    "Parkinson",
    "enfermedad cardiovascular",
    "problemas de aprendizaje",
    "demencia",
    "síndrome de fatiga crónica",
    "enfermedad de la arteria coronaria",
    "infección del tracto respiratorio superior",
    "alopecia",
    "disfunción sexual",
    "daño nervioso",
    "síndrome del túnel carpiano",
    "insuficiencia hepática",
    "tinnitus",
    "malaria",
    "flebitis",
    "diarrea",
    "problemas de visión",
    "aneurisma aórtico",
    "infección del tracto urinario",
    "psicosis",
    "artritis reumatoide",
    "diabetes",
    "síndrome de Stevens-Johnson",
    "enfermedad mental",
    "pancreatitis",
    "adenomiosis",
    "ELA (esclerosis lateral amiotrófica)",
    "enfermedad renal crónica",
    "endometriosis",
    "asma",
    "lupus",
    "neumonía",
    "arritmia"
]

