data:
  input_file_path: '../Data/Stackexchange/stackexchange/stackexchange.jsonl'
  output_folder_path: '../Data/Filtered/Stackexchange'
  metadata_keys: 
    - "language"
    - "url"
    - "timestamp"
    - "question_score"
processing:
  remove_latex: true
  save_file: true
  filename: 'stackexchange_filtered.csv'
  total_texts_filename: 'tot_texts_stack.txt'
