cancer_keywords = [
    word.lower()
    for word in [
        # AIDS-Related Lymphoma
        "AIDS Associated Lymphoma",
        "HIV Associated Lymphoma",
        "AIDS Related Lymphoma",
        "HIV Related Lymphoma",
        "AIDS-Related Lymphoma",
        "HIV-Related Lymphoma",
        "AIDS-Associated Lymphoma",
        "HIV-Associated Lymphoma",
        # eye neoplasms
        "Eye Cancer",
        "Eye Neoplasm",
        "Cancer of Eye",
        "Cancer of the Eye",
        "Conjunctival Neoplasm",
        "Conjunctival cancer",
        "Intraocular Lymphoma",
        "Orbital Neoplasm",
        "Orbital cancer",
        "Ocular Paraneoplastic Syndrome",
        "Retinal Neoplasm",
        "Retinal cancer",
        "Retinoblastoma",
        "Uveal Neoplasm",
        "Uveal cancer",
        "Choroid Neoplasm",
        "Choroid cancer",
        "Iris Neoplasm",
        "Iris cancer",
        "Ocular Cancer",
        "Ocular Melanoma",
        # Wilms Tumor and Other Childhood Kidney Tumors
        "Wilm Tumor",
        "Wilms' Tumor",
        "Wilm's Tumor",
        "Wilm Tumour",
        "Wilms' Tumour",
        "Wilm's Tumour",
        "Wilms Tumor",
        "Wilms Tumour",
        "Nephroblastoma",
        "Denys-Drash Syndrome",
        "WAGR Syndrome",
        # Ovarian Tumors
        # "Ovarian Epithelial Carcinoma", duplicate
        "Granulosa Cell Tumor",
        "Granulosa Cell Tumour",
        "Hereditary Breast and Ovarian Cancer Syndrome",
        "Luteoma",
        "Meigs Syndrome",
        "Meig's Syndrome",
        "Sertoli-Leydig Cell Tumor",
        "Sertoli-Leydig Cell Tumour",
        # "Thecoma", duplicate
        "Krukenberg Tumor",
        "Krukenberg Tumour",
        "Brenner Tumor",
        "Brenner Tumour",
        # Primary Peritoneal Cancer
        "Peritoneal Neoplasm",
        "Peritoneal cancer",
        "Peritoneal Surface Malignancy",
        "Peritoneal Malignancy",
        "Peritoneal Surface Malignancies",
        "Peritoneal Malignancies",
        "Peritoneal Carcinomatosis",
        "Peritoneal Carcinomatoses",
        "Pseudomyxoma Peritonei",
        # Vaginal Cancer
        "Vaginal Neoplasm",
        "Vaginal Cancer",
        "Cancer of the Vagina",
        "Cancer of Vagina",
        "Vagina Cancers",
        "Vagina Cancer",
        "Vagina Squamous Cell Carcinoma",
        "Vagina SCC",
        "SCC of the Vagina",
        "Squamous Cell Carcinoma of the Vagina",
        "Vaginal Squamous Cell Carcinoma",
        "Vaginal SCC",
        # Vulvar Cancer
        "Vulvar Neoplasm",
        "Vulva Neoplasm",
        "Cancer of Vulva",
        "Cancer of the Vulva",
        "Vulva Cancer",
        "Vulvar Cancer",
        "Vulva Squamous Cell Carcinoma",
        "Vulva SCC",
        "SCC of the Vulva",
        "Squamous Cell Carcinoma of the Vulva",
        "Vulvar Squamous Cell Carcinoma",
        "Vulvar SCC",
        # head and neck neoplasms
        "Head, Neck Neoplasms",
        "Head and Neck Neoplasm",
        "Cancer of Head and Neck",
        "Head and Neck Cancer",
        "Cancer of the Head and Neck",
        "Upper Aerodigestive Tract Neoplasms",
        "Head Neoplasm",
        "Head Cancer",
        "Cancer of Head",
        "Cancer of the Head",
        "Neck Neoplasm",
        "Cancer of Neck",
        "Neck Cancer",
        "Cancer of the Neck",
        "Squamous Cell Carcinoma of the Head and Neck",
        # "Head and Neck Squamous Cell Carcinoma", duplicate
        # "Head and Neck SCC", duplicate
        # "SCC of the Head and Neck", duplicate
        # Facial
        "Facial Neoplasm",
        "Eyelid Neoplasm",
        # Oral/Oropharyngeal Cancer
        "Mouth Neoplasm",
        "Oral Neoplasm",
        "Cancer of Mouth",
        "Mouth Cancers",
        "Oral Cancer",
        "Cancer of the Mouth",
        "Mouth Cancer",
        "Gingival Neoplasm",
        "Congenital Epulides",
        "Congenital Epulis",
        "Oral Leukoplakia",
        "Oral Leukokeratoses",
        "Oral Leukokeratosis",
        "Oral Keratoses",
        "Lip Neoplasm",
        "Cancer of Lip",
        "Cancer of the Lip",
        "Lip Cancer",
        # "Oropharyngeal Neoplasm",   duplicate
        "Oropharynx Neoplasm",
        "Cancer of Oropharnyx",
        "Cancer of the Oropharynx",
        "Oropharnyx Cancer",
        # "Oropharyngeal Cancer", duplicate
        "Tonsil Neoplasm",
        "Tonsillar Neoplasm",
        "Cancer of Tonsil",
        "Cancer of the Tonsil",
        "Tonsil Cancer",
        "Tonsillar Cancer",
        "Tonsillar SCC",
        "Tonsillar Squamous Cell Carcinoma",
        "Gingival Cancer",
        "Gingival Carcinoma",
        "Cancer of the Gingiva",
        "Gingival Squamous Cell Carcinoma",
        # "Gingival SCC", duplicate
        "Gum Cancer",
        "Cancer of the Gums",
        "Buccal Cancer",
        "Buccal Carcinoma",
        # "Buccal Squamous Cell Carcinoma", duplicate
        # "Buccal SCC",  # duplicate
        # ENT
        "Otorhinolaryngologic Neoplasm",
        "Ootorhinolaryngeal Neoplasm",
        "Otorhinolaryngological Neoplasm",
        "Otorhinolaryngeal Cancer",
        "Ear Neoplasm",
        "Neoplasms of Ear Auricle",
        "Ear Auricle Neoplasm",
        "Auricular Neoplasm",
        "Cancer of Ear",
        "Ear Cancer",
        "Cancer of the Ear",
        "Ear Auricle Cancer",
        "Auricular Cancer",
        "ethmoid sinus cancer",
        "esthesioneuroblastoma",
        "nasal cavity cancer",
        "Laryngeal Neoplasm",
        "Larynx Neoplasm",
        "Cancer of Larynx",
        "Larynx Cancer",
        "Laryngeal Cancer",
        "supraglottic Neoplasm",
        "Cancer of supraglottic larynx",
        "Cancer of supraglottis",
        "supraglottic Cancer",
        "supraglottis Cancer",
        "glottic Neoplasm",
        "Cancer of glottis",
        "glottic Cancer",
        "subglottic Neoplasm",
        "Cancer of subglottic larynx",
        "Cancer of subglottis",
        "subglottic Cancer",
        "subglottis Cancer",
        "hypopharyngeal Neoplasm",
        "hypopharynx Neoplasm",
        "Cancer of hypoparynx",
        "hypopharynx Cancer",
        "hypopharyngeal Cancer",
        "Oral cavity Neoplasm",
        "Cancer of oral cavity",
        "oral cavity Cancer",
        # "oropharynx Neoplasm", duplicate
        "Cancer of oropharynx",
        "oropharynx Cancer",
        "oropharyngeal Neoplasm",
        "oropharyngeal Cancer",
        "tongue cancer",
        "cancer of the tongue",
        "base of tongue cancer",
        "cancer of the base of tongue",
        # "lip cancer", duplicate
        "cancer og the lip",
        "Nose Neoplasm",
        "Nasal Neoplasm",
        "Cancer of Nose",
        "Nose Cancer",
        "Nasal Cancer",
        "Cancer of the Nose",
        "Pharyngeal Neoplasm",
        "Pharynx Neoplasm",
        "Cancer of Pharynx",
        "Pharynx Cancer",
        "Cancer of the Pharynx",
        "Pharyngeal Cancer",
        # "Nasopharyngeal Carcinoma", duplicate
        # "Tonsillar Neoplasm", duplicate
        "SCC of the Head and Neck",
        "Head and Neck SCC",
        "Head And Neck Squamous Cell Carcinoma",
        # "Squamous Cell Carcinoma of the Head and Neck", duplicate
        # "Squamous Cell Carcinoma of the Larynx", duplicate
        "Oral Tongue Squamous Cell Carcinoma",
        "Tongue Squamous Cell Carcinoma",
        # "Hypopharyngeal Squamous Cell Carcinoma", duplicate
        "Oral Squamous Cell Carcinoma",
        "Oropharyngeal Squamous Cell Carcinoma",
        "SCC of the Larynx",
        "Oral Tongue SCC",
        "Tongue SCC",
        "Hypopharyngeal SCC",
        "Oral SCC",
        "Oropharyngeal SCC",
        "Nasopharyngeal Cancer",
        "Cancer of the Nasopharynx",
        "Nasopharyngeal Carcinoma",
        "Carcinoma of the Nasopharynx",
        "SCC of the Nasopharynx",
        "NUT midline tumor",
        "NUT midline tumour",
        # "lip squamous cell carcinoma", duplicate
        "squamous cell carcinoma of the lip",
        # "tonsillar squamous cell carcinoma",
        "squamous cell carcinoma of the tonsil",
        "oral cavity squamous cell carcinoma",
        "squamous cell carcinoma of the oral cavity",
        "oropharynx squamous cell carcinoma",
        # "oropharyngeal squamous cell carcinoma", duplicate
        "squamous cell carcinoma of the oropharynx",
        "tonsil squamous cell carcinoma",
        "pharynx squamous cell carcinoma",
        "pharyngeal squamous cell carcinoma",
        "squamous cell carcinoma of the pharynx",
        "hypopharynx squamous cell carcinoma",
        "hypopharyngeal squamous cell carcinoma",
        "squamous cell carcinoma of the hypopharynx",
        # "tongue squamous cell carcinoma", duplicate
        "squamous cell carcinoma of the tongue",
        "base of tongue squamous cell carcinoma",
        "squamous cell carcinoma of the base of tongue",
        "larynx squamous cell carcinoma",
        "laryngeal squamous cell carcinoma",
        "squamous cell carcinoma of the larynx",
        "glottis squamous cell carcinoma",
        "glottic squamous cell carcinoma",
        "squamous cell carcinoma of the glottis",
        "subglottis squamous cell carcinoma",
        "subglottic squamous cell carcinoma",
        "squamous cell carcinoma of the subglottis",
        "supraglottis squamous cell carcinoma",
        "supraglottic squamous cell carcinoma",
        "squamous cell carcinoma of the supraglottis",
        "nasopharynx squamous cell carcinoma",
        "nasopharyngeal squamous cell carcinoma",
        "squamous cell carcinoma of the nasopharynx",
        "gum squamous cell carcinoma",
        # "gum SCC", duplicate
        "squamous cell carcinoma of the gum",
        "buccal squamous cell carcinoma",
        "mouth squamous cell carcinoma",
        "squamous cell carcinoma of the mouth",
        "nasal cavity squamous cell carcinoma",
        "squamous cell carcinoma of the nasal cavity",
        "ethmoid sinus squamous cell carcinoma",
        "squamous cell carcinoma of the ethmoid sinus",
        # "oral squamous cell carcinoma", duplicate
        "gingiva squamous cell carcinoma",
        "squamous cell carcinoma of the gingiva",
        "lip squamous cell carcinoma",
        "SCC of the lip",
        # "tonsillar SCC", duplicate
        "SCC of the tonsil",
        "oral cavity SCC",
        "SCC of the oral cavity",
        "oropharynx SCC",
        # "oropharyngeal SCC", duplicate
        "SCC of the oropharynx",
        "tonsil SCC",
        "pharynx SCC",
        "pharyngeal SCC",
        "SCC of the pharynx",
        "hypopharynx SCC",
        # "hypopharyngeal SCC", duplicate
        "SCC of the hypopharynx",
        # "tongue SCC", duplicate
        "SCC of the tongue",
        "base of tongue SCC",
        "SCC of the base of tongue",
        "larynx SCC",
        "laryngeal SCC",
        # "SCC of the larynx", duplicate
        "glottis SCC",
        "glottic SCC",
        "SCC of the glottis",
        "subglottis SCC",
        "subglottic SCC",
        "SCC of the subglottis",
        "supraglottis SCC",
        "supraglottic SCC",
        "SCC of the supraglottis",
        "nasopharynx SCC",
        "nasopharyngeal SCC",
        # "SCC of the nasopharynx",
        # "gum squamous cell carcinoma",
        "gum SCC",
        "SCC of the gum",
        "buccal SCC",
        "mouth SCC",
        "SCC of the mouth",
        "nasal cavity SCC",
        "SCC of the nasal cavity",
        "ethmoid sinus SCC",
        "SCC of the ethmoid sinus",
        # "oral SCC",
        "gingival SCC",
        "gingiva SCC",
        "SCC of the gingiva",
        # Salivary Gland Cancer
        "Salivary Gland Neoplasm",
        "Salivary Gland Lymphadenoma",
        "Non-Sebaceous Lymphadenoma",
        "Cancer of Salivary Gland",
        "Cancer of the Salivary Gland",
        "Salivary Gland Cancer",
        "Sebaceous Lymphadenoma",
        "Parotid Neoplasm",
        "Cancer of Parotid",
        "Parotid Cancer",
        "Cancer of the Parotid",
        "Sublingual Gland Neoplasm",
        "Submandibular Gland Neoplasm",
        "Adenoid Cystic Carcinoma",
        "Pleomorphic Adenoma",
        "Acinic Cell Carcinoma",
        # "Clear Cell Carcinoma", duplicate
        "Warthin's tumor",
        "Warthin's tumour",
        "mucoepidermoid tumor",
        "mucoepidermoid tumour",
        "salivary dict carcinoma",
        "ex pleomorphic adnoma",
        "polymorphous adenocarcinoma",
        "epithelial-myoepithelial carcinoma",
        "sialoblastoma",
        # Central Nervous System Germ Cell Tumors
        "Germ Cell and Embryonic Neoplasm",
        "Germ Cell and Embryonal Neoplasm",
        "Neoplasms, Germ Cell",
        "Germ Cell Tumor",
        "Germ Cell Tumour",
        "Germ Cell Neoplasm",
        "Embryonal Neoplasm",
        "Embryonal Cancer",
        "Germ Cell Cancer",
        "Embryonal Carcinoma",
        # "Chordoma", duplicate
        "Germinoma",
        "Dysgerminoma",
        "Disgerminoma",
        "Seminoma",
        "Gonadoblatoma",
        "Mesonephroma",
        "Endodermal Sinus Tumor",
        "Endodermal Sinus Tumour",
        "Yolk Sac Tumor",
        "Yolk Sac Tumour",
        "Teratocarcinomas",
        "Teratomas",
        "Dysembryoma",
        # "Teratoid Tumour", duplicate
        "Benign Teratoma",
        "Malignant Teratoma",
        "Immature Teratoma",
        "Dermoid Cyst",
        "Struma Ovarii",
        "Trophoblastic Neoplasm",
        "Trophoblastic Tumor",
        "Trophoblastic Tumour",
        "Trophoblast Neoplasm",
        "Trophoblast Tumour",
        "Trophoblastic Cancer",
        "Trophoblast Cancer",
        "Choriocarcinomas",
        "Hyatidiform Mole",
        # Kaposi Sarcoma
        "Kaposi's Sarcoma",
        "Kaposis Sarcoma",
        "Multiple Idiopathic Pigmented Hemangiosarcoma",
        "Kaposi Sarcoma",
        # Breast Cancer
        "Breast Neoplasm",
        "Breast Tumor",
        "Breast Tumour",
        "Breast Cancer",
        "Mammary Cancer",
        "Neoplasm of Breast",
        "Tumour of Breast",
        "Tumor of Breast",
        "Cancer of Breast",
        "Cancer of the Breast",
        "Mammary Carcinoma",
        "Mammary Neoplasm",
        "Breast Carcinoma",
        "Carcinoma of the breast",
        "Paget's Disease of the breast",
        # "Hereditary Breast and Ovarian Cancer Syndrome", duplicate
        "Inflammatory Breast Neoplasm",
        "Inflammatory Breast cancer",
        "Triple Negative Breast Neoplasm",
        "Triple Negative Breast cancer",
        "Paget's disease",
        " DCIS ",
        "ductal carcinoma in situ",
        "phylloides tumor",
        "phylloides tumour",
        # endocrine gland neoplasms
        "Endocrine Gland Neoplasm",
        "Carcinoma of Endocrine Gland",
        "Endocrine Gland Carcinoma",
        "Endocrine Cancer",
        "Endocrine Gland Cancer",
        "Cancer of Endocrine Gland",
        "Cancer of the Endocrine Gland",
        "Adrenal Gland Neoplasms",
        "Adrenal Gland cancer",
        "Multiple Endocrine Neoplasia",
        "Ovarian epithelial Carcinoma",
        # "Granulosa Cell Tumor", duplicate
        # "Granulosa Cell Tumour", duplicate
        # "Hereditary Breast and Ovarian Cancer Syndrome",  #look at duplicates in keywords -> can duplicate in dictionary
        # "Luteoma",
        # "Meigs Syndrome", duplicate
        # "Sertoli-Leydig Cell Tumor", # look at duplicates in keywords -> can duplicate in dictionary
        # "Sertoli-Leydig Cell Tumour", # look at duplicates in keywords -> can duplicate in dictionary
        "Thecoma",
        # "Islet Cell Adenoma", duplicate
        "Islet Cell Carcinoma",
        "Pancreatic Ductal Carcinoma",
        "Pancreatic Intraductal Neoplasm",
        "Parathyroid Neoplasm",
        "Parathyroid cancer",
        "ACTH-Secreting Pituitary Adenoma",
        "Growth Hormone-Secreting Pituitary Adenoma",
        "Prolactinoma",
        "Papillary Thyroid Cancer"
        # carcinoma, neuroendocrine
        "Neuroendocrine Carcinoma",
        "Neuroendocrine Cancer",
        "Medullary Carcinoma",
        "Medullary Cancer",
        "Merkel Cell Cancer",
        "Somatostatinoma",
        "Vipoma",
        # Adrenocortical Carcinoma
        "Adrenocortical Carcinomas",
        "Adrenal Cortical Carcinoma",
        "Adrenal Carcinoma",
        "Adrenal Cancer",
        # Neuroendocrine Carcinoma of the Skin (Merkel Cell Carcinoma)
        "Merkel Tumors",
        "Merkel Tumours",
        "Merkel Cell Tumor",
        "Merkel Cell Tumour",
        # Merkel Cell ",
        "Merkel Cell Carcinoma",
        # Parathyroid Cancer
        # "Parathyroid Neoplasm", duplicate
        "Parathyroid Adenoma",
        "Parathyroid Carcinoma",
        "Cancer of Parathyroid",
        # "Parathyroid Cancer", duplicate
        # "Cancer of the Parathyroid", duplicate
        # Paraganglioma
        "Paragangliomas",
        "Gangliocytic Paraganglioma",
        "Gangliocytic Paragangliomas",
        "Paragangliomata",
        "Carotid Body Tumor",
        "Glomus Jugulare Tumor",
        "Glomus Tympanicum Tumor",
        "Carotid Body Tumour",
        "Glomus Jugulare Tumour",
        "Glomus Tympanicum Tumour",
        "jugular paraganglioma",
        "glomus tumor",
        "glomus tumour",
        # Pheochromocytoma
        "Pheochromocytoma",
        # Pituitary Tumor
        "Pituitary Neoplasm",
        "Pituitary Tumor",
        "Pituitary Tumour",
        "Pituitary Adenoma",
        "Pituitary Carcinoma",
        "Cancer of the Pituitary",
        "Pituitary Cancer",
        "Cancer of Pituitary",
        "Nelson Syndrome",
        "Prolactinoma"
        # Thyroid Cancer
        "Thyroid Neoplasm",
        "Thyroid Carcinoma",
        "Cancer of Thyroid",
        "Thyroid Cancer",
        "Cancer of the Thyroid",
        "Thyroid Adenoma",
        "Papillary Thyroid Cancer",
        "Papillary Carcinoma Of Thyroid",
        "Papillary Thyroid Carcinoma",
        "Medullary Thyroid Cancer",
        "Medullary Thyroid Carcinoma",
        "Anaplastic Thyroid Cancer",
        "Anaplastic Thyroid Carcinoma",
        "Follicular Thyroid Cancer",
        "Follicular Thyroid Carcinoma",
        "Papillary Cancer Of Thyroid",
        "Anaplastic Cancer Of Thyroid",
        "Medullary Cancer Of Thyroid",
        "Follicular Cancer Of Thyroid",
        "Anaplastic Carcinoma Of Thyroid",
        "Medullary Carcinoma Of Thyroid",
        "Follicular Carcinoma Of Thyroid",
        # "Parathyroid Cancer", duplicate
        # "Parathyroid Carcinoma",
        "Cancer of the Parathyroid",
        "Carcinoma of the Parathyroid",
        # Neuroendocrine Tumors NOS
        "Apudoma",
        "Carcinoid Tumor",
        "Carcinoid Tumour",
        "Malignant Carcinoid Syndrome",
        # Retinoblastoma
        "Retinoblastomas",
        "Retinal Neuroblastoma",
        "Retinal Glioma",
        "Retinal Glioblastoma",
        # Bladder Cancer
        "Urinary Bladder Neoplasm",
        "Bladder Tumor",
        "Bladder Tumour",
        "Bladder Neoplasm",
        "Malignant Tumor of Urinary Bladder",
        "Malignant Tumour of Urinary Bladder",
        "Cancer of the Bladder",
        "Bladder Cancer",
        "Cancer of Bladder",
        "Urothelial Cancer",
        "Urothelial Carcinoma",
        "Transitional Cell Carcinoma",
        # Kidney (Renal Cell) Cancer
        "Nephroid Carcinoma",
        "Adenocarcinoma Of Kidney",
        "Renal Cell Carcinoma",
        "Renal Cell Cancer",
        "Renal Adenocarcinoma",
        "Renal Carcinoma",
        "Renal Cell Adenocarcinoma",
        "Grawitz Tumor",
        "Grawitz Tumour",
        "Hypernephroid Carcinoma",
        "Collecting Duct Carcinoma of the Kidney",
        "Renal Collecting Duct Carcinoma",
        "Clear Cell Cancer",
        "Clear Cell Carcinoma",
        # Penile Cancer
        "Penis Neoplasm",
        "Penile Neoplasm",
        "Cancer of Penis",
        "Cancer of the Penis",
        "Penis Cancer",
        "Penile Cancer",
        "Penile Squamous Cell Carcinoma",
        "Penile SCC",
        # Prostate Cancer
        "Prostate Neoplasm",
        "Prostatic Neoplasm",
        "Prostate Cancer",
        "Cancer of the Prostate",
        "Prostatic Cancer",
        "Cancer of Prostate"
        # Renal Pelvis and Ureter Cancer, Transitional Cell
        "Transitional Cell Carcinoma",
        # Testicular Cancer
        "Testicular Neoplasm",
        "Testis Neoplasm",
        "Testicular Tumor",
        "Testicular Tumour",
        "Cancer of Testis",
        "Testis Cancer",
        "Cancer of the Testes",
        "Cancer of the Testis",
        "Testicular Cancer",
        "Tumor of Rete Testis",
        "Rete Testis Tumor",
        "Testis Tumor, Rete",
        "Leydig Cell Tumor",
        "Sertoli Cell Tumor",
        "Tumour of Rete Testis",
        "Rete Testis Tumour",
        "Testis Tumour, Rete",
        "Leydig Cell Tumour",
        "Sertoli Cell Tumour",
        # Urethral Cancer
        "Urethra Neoplasm",
        "Urethral Neoplasm",
        "Cancer of Urethra",
        "Urethra Cancer",
        "Urethral Cancer",
        "Cancer of the Urethra"
        # Cervical Cancer
        "Uterine Cervical Neoplasm",
        "Cervical Neoplasm",
        "Cervix Neoplasm",
        "Cancer of the Uterine Cervix",
        "Cancer of the Cervix",
        "Cervical Cancer",
        "Uterine Cervical Cancer",
        "Cancer of Cervix",
        "Cervix Cancer",
        "Cervical Squamous Cell Carcinoma",
        "Cervical SCC",
        "Cervix Squamous Cell Carcinoma",
        "Cervix SCC",
        "SCC of the Cervix",
        "Squamous Cell Carcinoma of the Cervix",
        # Endometrial Cancer
        "Endometrial Neoplasm",
        "Endometrial Carcinoma",
        "Endometrial Cancer",
        "Endometrium Cancer",
        "Cancer of the Endometrium",
        "Carcinoma of Endometrium",
        "Carcinoma of uterus",
        "adenocarcinoma of Endometrium",
        "adenocarcinoma of uterus",
        "Endometrium Carcinoma",
        "Cancer of Endometrium",
        "Endometrium Cancers",
        "Endometrial Stromal Tumors",
        "Endometrial Stromal Tumours",
        "Carcinoma, Endometrioid",
        "Uterine Neoplasm",
        "Uterine Carcinoma",
        "Uterine Cancer",
        "Cancer of the uterus",
        "endometrial adenocarcinoma",
        "uterine adenocarcinoma",
        "uterine sarcoma",
        # Fallopian Tube Cancer
        "Fallopian Tube Neoplasm",
        "Fallopian Tube Cancer",
        "Cancer of the Fallopian Tube",
        # leukemia
        # "Leukemia", duplicate see later
        "Leucocythaemia",
        "Leucocythemia",
        # Acute Lymphoblastic Leukemia
        "Acute Lymphoblastic Leukemia",
        "Acute Lymphocytic Leukemia",
        "Acute Lymphoid Leukemia",
        " ALL ",
        # Acute Myeloid Leukemia
        "Acute Myeloid Leukemia",
        "Acute Myeloblastic Leukemia",
        "Acute Myelocytic Leukemia",
        "Acute Nonlymphoblastic Leukemia",
        "Acute Nonlymphocytic Leukemia",
        "Acute Myelogenous Leukemia",
        " AML ",
        "Choloroma",
        "myeloid sarcoma",
        "myeloblastoma",
        "granulocytic sarcinoma",
        # Chronic Lymphocytic Leukemia
        "Small-Cell Lymphoma",
        "Small Cell Lymphoma",
        "Chronic Lymphocytic Lymphoma",
        "Chronic Lymphoblastic Leukemia",
        "Chronic B-Cell Leukemia",
        "Chronic Lymphocytic Leukemia",
        "Chronic Lymphatic Leukemia",
        "Small Lymphocytic Lymphoma",
        " CLL ",
        # Chronic Myelogenous Leukemia
        "Chronic Granulocytic Leukemia",
        "Chronic Myeloid Leukemia",
        "Chronic Myelocytic Leukemia",
        "Chronic Myelogenous Leukemia",
        " CML ",
        # Hodgkin Lymphoma
        "Hodgkin's Granuloma",
        "Hodgkins Granuloma",
        "Malignant Lymphogranuloma",
        "Hodgkin Lymphoma",
        "Hodgkin's Disease",
        "Hodgkin's Lymphoma",
        "Hodgkins Lymphoma",
        "Hodgkins Disease",
        "Hodgkin Granuloma",
        # Mycosis Fungoides
        "Mycosis Fungoides",
        "Pagetoid Reticulosis",
        # Non-Hodgkin Lymphoma
        "Diffuse Small Cleaved-Cell Lymphoma",
        "Diffuse Small Cleaved Cell Lymphoma",
        "Non-Hodgkins Lymphoma",  # how do we deal with hodgkin's and non-hodgkin's on regex? only include hyphen and accept above includes nonhodgkin's?
        "Non-Hodgkin's Lymphoma",
        "Non Hodgkin's Lymphoma",
        "Non-Hodgkin Lymphoma",
        "Non Hodgkin Lymphoma",
        "Burkitt Lymphoma",
        "mantle cell lymphoma",
        "marginal zone lymphoma",
        "MALT lymphoma",
        "extranodal marginal zone lymphoma",
        "Follicular lymphoma",
        "diffuse large B-cell lymphoma",
        " DLBCL ",
        # "small lymphocytic lymphoma", duplicate
        "orbital lymphoma",
        "high grade B-cell lymphoma",
        "B-cell lymphoma",
        "triple-hit lymphoma",
        "double-hit lymphoma",
        "gray zone lymphoma",
        "primary cutaneous diffuse-large b-cell lymphoma",
        "primary cutaneous DLBCL",
        "testicular lymphoma",
        "primary CNS lymphoma",
        "primary central nervous system lymphoma",
        # Sézary Syndrome
        "Sezary's Lymphoma",
        "Sezary Lymphoma",
        "Sezarys Lymphoma",
        "Sezary Erythroderma",
        # Waldenström Macroglobulinemia
        "Lymphoplasmacytoid Lymphoma",
        "Waldenstrom's Macroglobulinemia",
        "Waldenstroms Macroglobulinemia",
        "Waldenstrom's Macroglobulinaemia",
        "Waldenstrom Macroglobulinaemia",
        "Waldenstroms Macroglobulinaemia",
        # Langerhans Cell Histiocytosis
        "Hand-Schueller-Christian Syndrome",
        "Hand Schueller Christian Syndrome",
        "Hand-Schüller-Christian Disease",
        "Hand Schüller Christian Disease",
        "Hand-Schüller-Christian Syndrome",
        "Hand Schüller Christian Syndrome",
        "Histiocytosis X",
        "Generalized Histiocytoses",
        "Generalized Histiocytosis",
        "Histiocytoses, Generalized",
        "Histiocytosis-X",
        "Langerhans Cell Histiocytosis",
        "Langerhans Cell Histiocytoses",
        "Langerhans-Cell Granulomatosis",
        "Langerhans-Cell Histiocytosis",
        "Letterer-Siwe Disease",
        "Letterer Siwe Disease",
        "Schueller-Christian Disease",
        "Schueller Christian Disease",
        "Type 2 Histiocytosis",
        "Type 2 Histiocytoses",
        "Langerhans Cell Granulomatosis",
        "Langerhans Cell Granulomatoses",
        "Hand-Schueller-Christian Disease",
        "Hand Schueller Christian Disease",
        # Myelodysplastic Syndromes
        "Myelodysplastic Syndrome",
        "Dysmyelopoietic Syndrome",
        "Myelodysplasia",
        # hematologic neoplasms
        "Hematologic Neoplasm",
        "Hematologic Malignancies",
        "Hematologic Malignancy",
        "Hematological Neoplasm",
        "Blood Cancer",
        "Hematological Malignancy",
        "Hematopoietic Neoplasm",
        "Hematopoietic Malignancies",
        "Hematopoietic Malignancy",
        "Bone Marrow Neoplasm",
        "Primary Polycythemia",
        "Polycythemia Rubra Vera",
        "Polycythemia Ruba Vera",
        "Osler-Vaquez Disease",
        "Osler Vaquez Disease"
        # Bone Cancer
        "Bone Neoplasm",
        "Bone Cancer",
        "Cancer of the Bone",
        "Cancer of Bone",
        "Adamantinomas",
        "Adamantinoma"
        # Ewing Sarcoma
        "Ewing's Sarcoma",
        "Ewings Sarcoma",
        "Ewing's Tumor",
        "Ewings Tumor",
        "Ewing's Tumour",
        "Ewings Tumour",
        "Ewing Sarcoma",
        "Ewing Tumor",
        "Ewing Tumour",
        # Osteosarcoma and Undifferentiated Pleomorphic Sarcoma of Bone Treatment
        "Osteosarcomas",
        "Osteosarcoma Tumor",
        "Osteosarcoma Tumors",
        "Osteosarcoma Tumour",
        "Osteosarcoma Tumours",
        "Sarcoma, Osteogenic",
        "Osteogenic Sarcomas",
        "Osteogenic Sarcoma",
        "Osteosarcoma, Juxtacortical",
        "osteosarcoma",
        # Chordoma
        "Chordoma",
        # Rhabdomyosarcoma
        "Rhabdomyosarcomas",
        "Rhabdomyosarcoma",
        # Soft Tissue Sarcoma
        "Soft Tissue Sarcoma",
        "Soft Tissue Sarcomas",
        "Epithelioid Sarcoma",
        "Epithelioid Sarcomas",
        "Spindle Cell Sarcoma",
        "Spindle Cell Sarcomas" "Alveolar Sarcoma",
        "Alveolar Sarcomas",
        "desmoid tumor",
        "desmoid tumour",
        "retroperitoneal sarcinoma",
        "chondrosarcoma",
        # Brain Tumor
        "Brain Neoplasm",
        "Brain Tumor",
        "Brain Tumour",
        "Intracranial Neoplasm",
        "Brain Metastase",
        "Brain Cancer",
        "Cancer of Brain",
        "Cancer of the Brain",
        "Cerebroventricular Neoplasm",
        "Intraventricular Neoplasm",
        "Cerebral Ventricle Tumour",
        "Brain Ventricular Tumor",
        "Brain Ventricular Tumour",
        "Brain Ventricular Neoplasms",
        "Cerebral Ventricle Neoplasm",
        "Choroid Plexus Tumor",
        "Choroid Plexus Tumour",
        "Choroid Plexus Neoplasm",
        "Primary Choroid Plexus Neoplasms",
        "Choroid Plexus Papillomas",
        "Papilloma of Choroid Plexus",
        "Choroid Plexus Papilloma",
        "Infratentorial Neoplasm",
        "Posterior Fossa Tumor",
        "Posterior Fossa Tumour",
        "Infratentorial Tumor",
        "Infratentorial Tumour",
        "Posterior Fossa Neoplasm",
        "Infratentorial Cancer",
        "Brain Stem Neoplasm",
        "Brainstem Neoplasm",
        "Brainstem Tumor",
        "Brain Stem Tumor",
        "Pontine Tumor",
        "Brainstem Tumour",
        "Brain Stem Tumour",
        "Pontine Tumour",
        "Pontine Neoplasm",
        "Mesencephalic Neoplasm",
        "Midbrain Tumor",
        "Midbrain Tumour",
        "Midbrain Neoplasm",
        "Medullary Neoplasm",
        "Medullary Tumor",
        "Medullary Tumour",
        "Cerebellar Tumor",
        "Cerebellar Tumour",
        "Cerebellar Neoplasm",
        "Cerebellar Cancer",
        "Cerebellar Cancers",
        "Neurocytomas",
        "Central Neurocytoma",
        "Pinealomas",
        "Pineal Gland Tumor",
        "Pineal Tumors",
        "Pineal Tumor",
        "Pineal Gland Tumour",
        "Pineal Tumours",
        "Pineal Tumour",
        "Pineal Neoplasm",
        "Pineoblastoma",
        "Pinealocytoma",
        "Pineocytoma",
        "Supratentorial Tumor",
        "Supratentorial Tumour",
        "Supratentorial Neoplasm",
        "Supratentorial Cancer",
        "Hypothalamus Neoplasm",
        "Hypothalamus Tumor",
        "Hypothalamic Tumor",
        "Hypothalamus Tumour",
        "Hypothalamic Tumour",
        "Hypothalamic Neoplasm",
        "Hypothalamic Cancer",
        "Hypothalamic Teratoma",
        # Astrocytomas
        "Astroglioma",
        "Astrocytic Glioma",
        "Astrocytoma",
        "Glioblastoma",
        " GMB ",
        "Anaplastic Astrocytoma",
        # "Anaplastic glioma", # look at duplicates in keywords -> can duplicate in dictionary
        "Oligoastrocytoma",
        "pilocytic astrocytoma",
        # Oligodendroglioma
        "Oligodendroglioma",
        # Gliomas
        "Gliomas",
        "Glial Cell Tumor",
        "Glial Cell Tumour",
        "Mixed Glioma",
        "Mixed Gliomas",
        "Malignant Glioma",
        "Malignant Gliomas",
        "anaplastic glioma",
        "low grade glioma",
        "high grade glioma",
        "low-grade glioma",
        "high-grade glioma",
        "diffuse intrinsic midline glioma",
        "glioma",
        "tectal glioma",
        "gliomatosis cerebri",
        # Central Nervous System Atypical Teratoid/Rhabdoid Tumor
        "Rhabdoid Tumor",
        "Rhabdoid Tumour",
        # "Teratomas", duplicate
        # "Dysembryoma", duplicate
        "Teratoid Tumor",
        "Teratoid Tumour",
        "Atypical Teratoid/Rhabdoid Tumour",
        "Atypical Teratoid/Rhabdoid Tumor",
        " ATRT ",
        # Medulloblastoma and Other Central Nervous System Embryonal Tumors
        "Medulloblastoma",
        # Craniopharyngioma
        "Craniopharyngiomas",
        "Rathke's Pouch Tumor",
        "Rathkes Pouch Tumor",
        "Rathke Pouch Tumor",
        "Rathke's Pouch Tumour",
        "Rathkes Pouch Tumour",
        "Rathke Pouch Tumour",
        # "Rathke's Cleft Neoplasm", duplicate
        "Rathkes Cleft Neoplasm",
        "Rathke Cleft Neoplasm",
        # Ependymoma
        "Ependymomas",
        "ependymoma",
        # Neuroblastoma
        "Neuroblastomas",
        "Ganglioneuroblastoma",
        "neuroblastoma",
        # neuroepithelial neoplasms
        "astroblastoma",
        "Ependymoastrocytoma",
        "Melanotic Neuroectodermal Tumor",
        "Melanotic Neuroectodermal Tumour",
        "Retinal Anlage Tumour",
        "Retinal Anlage Tumor",
        "Melanoameloblastoma",
        "Melanotic Progonoma",
        "Neuroendocrine Tumor",
        "Neuroendocrine Tumour",
        # Meningioma
        "Meningioma",
        "meningiomas",
        # Benign CNS tumors NOS
        "hemangiopericytoma",
        # "craniopharyngioma", duplicate
        "Craniopharyngioma",
        # "Rathke's Pouch Tumor", duplicate
        # "Rathke's Pouch Tumour",
        "Rathke's Cleft Neoplasm",
        "Papillary Craniopharyngioma",
        "Adamantinous Craniopharyngioma",
        "Neurilemmoma",
        "Acoustic Neuroma",
        "vestibular schwannoma",
        "solitary fibrous tumor",
        "solitary fibrous tumour",
        # Lung cancer
        "Lung Cancer," "tracheal cancer",
        # Lung Cancer, Non-Small Cell
        "Non-Small-Cell Lung Carcinomas",
        "Non-Small-Cell Lung Carcinoma",
        "Non Small Cell Lung Carcinoma",
        "Non-Small Cell Lung Carcinoma",
        "Non-Small Cell Lung Cancer",
        "Nonsmall Cell Lung Cancer",
        " NSCLC ",
        "lung adenocarcinoma",
        "adenocarcinoma of the lung",
        "lung squamous cell carcinoma",
        "lung SCC",
        "SCC of the lung",
        "squamous cell carcinoma of the lung",
        # Lung Cancer, Small Cell
        "Small Cell Lung Cancer",
        "Small Cell Cancer of the Lung",
        "Oat Cell Lung Cancer",
        "Oat Cell Carcinoma",
        " SCLC ",
        "ES-SCLC",
        "LS-SCLC",
        "extensive stage-SCLC",
        "limited stage-SCLC",
        # Malignant Mesothelioma
        "Malignant Mesothelioma",
        "Malignant Pleural Mesothelioma",
        "Mesothelioma",
        # Thymoma and Thymic Carcinoma
        "Thymomas",
        "Thymic Carcinoma",
        "Thymoma",
        # T-Cell Lymphoma, Cutaneous
        "Cutaneous T-Cell Lymphoma",
        "Cutaneous T Cell Lymphoma",
        # T-Cell Lympphoma
        "T-cell lymphoma",
        "T cell lymphoma",
        "NK-T cell lymphoma",
        "anaplastic large cell lymphoma",
        # neoplasms, unknown primary
        "Occult Primary Neoplasms",
        "Occult Primary Neoplasm",
        "Primary Neoplasms, Occult",
        "Unknown Primary Neoplasms",
        "Unknown Primary Neoplasm",
        "Unknown Primary Tumor",
        "Unknown Primary Tumour",
        "Unknown Primary Neoplasm Metastasis",
        "Squamous Cell Carcinoma of Unknown Primary",
        "SCC of Unknown Primary",
        "Cancer of Unknown Primary",
        "Carcinoma of Unknown Primary",
        # Melanoma
        "Melanomas",
        "Malignant Melanoma",
        "Malignant Melanomas",
        "Hutchinson's Melanotic Freckle",
        # Skin Cancer
        "Skin Neoplasm",
        "Cancer of Skin",
        "Cancer of the Skin",
        "Skin Cancer",
        "Acanthoma",
        "Muir-Torre Syndrome",
        # "squamous cell carcinoma", duplicate
        # " SCC ",  # space before and after duplicate
        "basal cell carcinoma",
        "melanoma",
        # Anal Cancer
        "Anal Neoplasm",
        "Anus Neoplasm",
        "Anal Cancer",
        "Cancer of the Anus",
        "Cancer of Anus",
        "Anus Cancer",
        "Anal SCC ",
        "Anal Squamous Cell Carcinoma",
        "Squamous Cell Carcinoma of the Anus",
        "SCC of the Anus",
        # Appendix Cancer
        "Appendiceal Neoplasm",
        "Appendiceal Cancer",
        "Cancer of the Appendix",
        "Appendix Cancer",
        "Cancer of Appendix"
        # Bile Duct Cancer
        "Bile Duct Neoplasm",
        "Bile Duct Cancer",
        "Cancer of the Bile Duct",
        "Cancer of Bile Duct",
        "Cholangiocarcinoma",
        "Intrahepatic cholangiocarcinoma",
        "Extrahepatic cholangiocarcinoma",
        "Biliary cancer",
        "Biliar carcinoma",
        # Colon Cancer
        "Colonic Neoplasm",
        "Colon Neoplasm",
        "Cancer of Colon",
        "Colon Cancer",
        "Cancer of the Colon",
        "Colonic Cancer",
        "Colonic Cancers",
        "Colon Adenocarcinoma",
        "Colon Adenocarcinomas",
        "appendiceal carcinoma",
        "sigmoid carcinoma",
        "ileocecal carcinoma",
        "cecal carcinoma",
        "rectosigmoid carcinoma",
        "rectal carcinoma",
        "rectal adenocarcinoma",
        "rectal cancer",
        "sigmoid cancer",
        "sigmoid adenocarcinoma",
        "rectosigmoid cancer",
        "rectosigmoid adenocarcinoma",
        "bowel cancer",
        "bowel carcinoma",
        "bowel adenocarcinoma",
        "cancer of the bowel",
        "intestinal cancer",
        "cancer of the intestines",
        "intestinal carcinoma",
        "intestinal adenocarcinoma",
        # Esophageal Cancer
        "Esophageal Neoplasm",
        "Esophagus Neoplasm",
        "Cancer of Esophagus",
        "Cancer of the Esophagus",
        "Esophagus Cancer",
        "Esophageal Cancer",
        "Esophageal Squamous Cell Carcinoma",
        "Esophageal SCC",
        "Esophageal adenocarcinoma",
        # Gallbladder Cancer
        "Gallbladder Neoplasm",
        "Cancer of Gallbladder",
        "Gallbladder Cancers",
        "Gallbladder Cancer",
        "Gall Bladder Cancer",
        "Gall Bladder Cancers",
        "Cancer of the Gallbladder",
        # "Cholangiocarcinoma", duplicate
        "Gallbladder carcinoma",
        "Gallbladder adenocarcinoma",
        "Gallbladder squamous cell carcinoma",
        "Gallbladder SCC",
        # Gastrointestinal Stromal Tumors (GIST)
        "Gastrointestinal Stromal Neoplasms",
        "Gastrointestinal Stromal Tumor",
        "Gastrointestinal Stromal Tumour",
        "Gastrointestinal Stromal Neoplasm",
        "Gastrointestinal Stromal Sarcoma",
        # Islet Cell Tumors, Pancreatic Neuroendocrine Tumors
        "Islet Cell Adenoma",
        "Islet Cell Tumor",
        "Islet of Langerhans Tumor",
        "Island Cell Tumor",
        "Islet Cell Tumour",
        "Islet of Langerhans Tumour",
        "Island Cell Tumour",
        "Nesidioblastoma",
        # Liver Cancer
        "Liver Neoplasm",
        "Hepatic Neoplasm",
        "Cancer of Liver",
        "Hepatocellular Cancer",
        "Hepatocellular Cancers",
        "Hepatic Cancer",
        "Hepatic Cancers",
        "Liver Cancer",
        "Liver Cancers",
        "Cancer of the Liver",
        " HCC ",
        # "Intrahepatic cholangiocarcinoma", duplicate
        # "cholangiocarcinoma", duplicate
        # Pancreatic Cancer
        "Pancreatic Neoplasm",
        "Pancreas Neoplasm",
        "Cancer of Pancreas",
        "Pancreas Cancer",
        "Pancreatic Cancer",
        "Cancer of the Pancreas",
        "Insulinoma",
        "Gastrinoma",
        "Glucagonoma",
        # "Somatostatinoma", duplicate
        # "Vipoma", duplicate
        "Pancreatic Intraductal Neoplasm" "Pancreatic adenocarcinoma",
        "Adenocarcinoma of the pancreas",
        "Pancreatic Carcinoma",
        "Pancreas adenocarcinoma",
        "Pancreas Carcinoma",
        # Stomach (Gastric) Cancer
        "Stomach Neoplasm",
        "Gastric Neoplasm",
        "Cancer of Stomach",
        "Cancer of the Stomach",
        "Gastric Cancer, Familial Diffuse",
        "Adenocarcinoma of the stomach",
        "Stomach Carcinoma",
        "GEJ tumor",
        "GEJ tumour",
        "Diffuse stomach cancer",
        "GEJ Cancer",
        "GEJ adenocarcinoma",
        "GEJ carcinoma",
        "GE junction tumor",
        "GE junction tumour",
        "GE junction Cancer",
        "GE junction adenocarcinoma",
        "GE junction carcinoma",
        "gastroesophageal junction tumor",
        "gastroesophageal junction tumour",
        "gastroesophageal junction cancer",
        "gastroesophageal junction adenocarcinoma",
        "gastroesophageal junction carcinoma",
        "stomach adenocarcinoma",
        # "stomach carcinoma", duplicate
        "stomach tumor",
        "stomach tumour",
        "stomach Cancer",
        "gastric adenocarcinoma",
        "gastric carcinoma",
        "gastric tumor",
        "gastric tumour",
        "gastric Cancer",
        # GI cancer
        "GI cancer",
        "gastrointestinal cancer",
        # Multiple myeloma
        "Multiple Myeloma",
        "Plasma-Cell Myeloma",
        "Myelomatosis",
        "Myelomatoses",
        "Plasma Cell Myeloma",
        "Kahler Disease",
        "Multiple-Myeloma",
        "plasmacytoma"
        # general cancer terms
        "cancer",
        "carcinoma",
        "adenocarcinoma",
        "squamous cell carcinoma",
        "adenosquamous carcinoma",
        " SCC ",
        "tumor",
        "tumour",
        "neoplasm",
        "malignancy",
        "malignant",
        "cancerous",
        "neoplastic",
        "lymphoma",
        "leukemia",
        "sarcoma",
        "myeloma",
        "mixed type cancer",
        "metastasis",
        "metastases",
        "oligometastasis",
        "oligometastases",
    ]
]
